### ISSUE TITLE
how to start sdorfehs?

### ISSUE THREAD

**Issue by drmarwat** [jcs/dotfiles#1]
I created a sdorfehs.desktop file in /usr/share/xsessions with following contents 
[Desktop Entry]
Encoding=UTF-8
Name=Sdorfehs
Comment=This session logs you into Sdorfeh
Exec=/usr/local/bin/sdorfeh
TryExec=/usr/local/bin/sdorfeh
Icon=
Type=Application
and tried to boot it from sddm but sdorfeh does not appear in sddm login menu
later I tried to boot it from .xinitrc file with exec sdorfehs disabling sddm but I can not login to sdorfeh. So how do I login to sdorfeh?

**Comment by jcs** [comment]
No idea
